name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ubah ke 'master' jika branch Anda bernama master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: ./couple-tracker # Masuk ke subfolder
        run: npm ci

      - name: Build Project
        working-directory: ./couple-tracker # Masuk ke subfolder
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./couple-tracker/dist # Target folder dist ada di sini
